name: Deploy Hexo Blog

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Hexo
        run: npx hexo generate

      - name: Deploy to Gitee Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITEE_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true